//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadConsultorioCardiologia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDConsultorioCardiologiaEntities : DbContext
    {
        public BDConsultorioCardiologiaEntities()
            : base("name=BDConsultorioCardiologiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<paCitaListar_Result> paCitaListar(string parametro3)
        {
            var parametro3Parameter = parametro3 != null ?
                new ObjectParameter("parametro3", parametro3) :
                new ObjectParameter("parametro3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paCitaListar_Result>("paCitaListar", parametro3Parameter);
        }
    
        public virtual ObjectResult<paHistorialListar_Result> paHistorialListar(string parametro4)
        {
            var parametro4Parameter = parametro4 != null ?
                new ObjectParameter("parametro4", parametro4) :
                new ObjectParameter("parametro4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paHistorialListar_Result>("paHistorialListar", parametro4Parameter);
        }
    
        public virtual ObjectResult<paPacienteListar_Result> paPacienteListar(string parametro2)
        {
            var parametro2Parameter = parametro2 != null ?
                new ObjectParameter("parametro2", parametro2) :
                new ObjectParameter("parametro2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPacienteListar_Result>("paPacienteListar", parametro2Parameter);
        }
    
        public virtual ObjectResult<paPersonalListar_Result> paPersonalListar(string parametro1)
        {
            var parametro1Parameter = parametro1 != null ?
                new ObjectParameter("parametro1", parametro1) :
                new ObjectParameter("parametro1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPersonalListar_Result>("paPersonalListar", parametro1Parameter);
        }
    
        public virtual ObjectResult<paUsuarioListar_Result> paUsuarioListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paUsuarioListar_Result>("paUsuarioListar", parametroParameter);
        }
    }
}
